export default interface Student {
    studentId: string;
    entMethod: string;
    entMethodDesc: string;
    groupId: string;
    admitTerm: string;
    admitYear: string;
    admitDate: string;
    sexCode: string;
    titleId: string;
    titleNameThai: string;
    titleShortEng: string;
    studNameThai: string;
    studSnameThai: string;
    studNameEng: string;
    studSnameEng: string;
    studyStatus: string;
    statusDescThai: string;
    stillStudent: string;
    yearStatus: string;
    nationality: string;
    citizenId: string;
    majorId: string;
    majorNameThai: string;
    majorNameEng: string;
    deptId: string;
    deptNameThai: string;
    deptNameEng: string;
    facId: string;
    facNameThai: string;
    facNameEng: string;
    campusId: string;
    campusNameThai: string;
    campusNameEng: string;
    coursePlanId: string;
    studyLevelId: string;
    studyLevelName: string;
    studyTypeId: string;
    studyTypeName: string;
    studyPlanId: string | null;
    studyPlanName: string | null;
    coursePlanDetail: string | null;
    regularYear: number | null;
    expandYear: number | null;
    courseCategoryId: string | null;
    courseCategoryNameThai: string | null;
    courseCategoryNameEng: string | null;
    degreeId: string | null;
    degreeNameThai: string;
    degreeNameEng: string;
    gradYear: string | null;
    gradDate: string | null;
    honourId: string | null;
    oecDate: string | null;
    birthDate: string;
    birthPlaceEng: string;
    birthPlaceThai: string;
    fieldOfStudyThai: string;
    fieldOfStudyEng: string;
    subMajorNameThai: string | null;
    subMajorNameEng: string | null;
    minorNameThai: string | null;
    minorNameEng: string | null;
    majorMinorNameThai: string;
}
